### ISSUE TITLE
Example codes do not work as expected

### ISSUE THREAD

**Issue by ashishsk** [adafruit/arduino-CAN#1]
Hi, 

I am trying to get the example codes from the Adafruit [page](https://learn.adafruit.com/adafruit-feather-m4-can-express/arduino-can-examples) to work on the new Feather M4 CAN boards, but it does not seem to work. 
Both the CAN Sender and CAN Receiver have the missing definition PIN_CAN_BOOSTEN. Even after defining them as the pin 4, I am unable to receive anything on the CAN receiver side. 

I have followed every step as described on the tutorial and yet I do not see the expected outputs (CAN Receiver just does not receive anything from the CAN Sender).

CAN Sender:
![image](https://user-images.githubusercontent.com/9916855/105882044-7e992200-6005-11eb-975c-2907d9d43939.png)

CAN Receiver 
![image](https://user-images.githubusercontent.com/9916855/105882132-98d30000-6005-11eb-8c25-e180cbd318c5.png)

Is there anything different on your test setup? Becasue I noticed that the example codes on the [repository ](https://github.com/adafruit/arduino-CAN/tree/master/examples) does not have the pin definitions for PIN_CAN_STANDBY and PIN_CAN_BOOSTEN as seen on the Adafruit [Learning ](https://learn.adafruit.com/adafruit-feather-m4-can-express/arduino-can-examples) page.

**Comment by ladyada** [comment]
closing as this should be resolved now. make sure to use the code examples on the learning guide!
