### ISSUE TITLE
CANReceiverCallback.ino example crashes on ESP32

### ISSUE THREAD

**Issue by jcwren** [adafruit/arduino-CAN#13]
- Arduino board:  Heltec WiFi LoRa V2

- Arduino IDE version (found in Arduino -> About Arduino menu):  n/a (PlatformIO 6.1.4)

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too):
* Compile and upload sketch

`onReceive()` is called from within an interrupt context. `Serial` functions on an ESP32 cannot be used from inside an interrupt. Attempting to do so results in the error below.  A better implementation would be to save the received CAN data to a structure and insert the structure into a FIFO. Check for new data within the `loop()` function and process accordingingly.
```
Guru Meditation Error: Core  1 panic'ed (Interrupt wdt timeout on CPU1).

Core  1 register dump:
PC      : 0x4008a54a  PS      : 0x00060735  A0      : 0x800897a2  A1      : 0x3ffbed0c
A2      : 0x3ffb8a00  A3      : 0x3ffb8890  A4      : 0x00000004  A5      : 0x00060723
A6      : 0x00060723  A7      : 0x00000001  A8      : 0x3ffb8890  A9      : 0x00000018
A10     : 0x3ffb8890  A11     : 0x00000018  A12     : 0x3ffc1694  A13     : 0x00060723
A14     : 0x007bee88  A15     : 0x003fffff  SAR     : 0x0000001c  EXCCAUSE: 0x00000006
EXCVADDR: 0x00000000  LBEG    : 0x400861d1  LEND    : 0x400861e1  LCOUNT  : 0xfffffffd
Core  1 was running in ISR context:
EPC1    : 0x400da427  EPC2    : 0x00000000  EPC3    : 0x00000000  EPC4    : 0x00000000


Backtrace:0x4008a547:0x3ffbed0c |<-CORRUPTED
```

**Comment by caternuson** [comment]
Yah, ESP32 support in this library is broken. This library is also being deprecated. The replacement library is here:
https://github.com/adafruit/Adafruit_CAN
which currently does not have ESP32 support. (SAME5x only). But any future attempts to add back in ESP32 support will show up there.
