### ISSUE TITLE
CAN Errors at low bitrates with Feather M4 CAN Board

### ISSUE THREAD

**Issue by TangoEcho** [adafruit/arduino-CAN#3]
- Arduino board:  Feather M4 CAN

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.13

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): When sending a CAN data packet at 125 kbps it sends out a bunch of error frames. The errors go away when tested at 500 kbps. 

`// Copyright (c) Sandeep Mistry. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

#include <CAN.h>

void setup() {
  Serial.begin(9600);
  while (!Serial);

  Serial.println("CAN Sender");

  // start the CAN bus at 125 kbps
  if (!CAN.begin(125E3)) {
    Serial.println("Starting CAN failed!");
    while (1);
  }
}

void loop() {
  uint8_t buf[8] = {11,179,13,123,123,0,0,1};
  // send packet: id is 11 bits, packet can contain up to 8 bytes of data
  Serial.print("Sending packet ... ");

  CAN.beginExtendedPacket(0xabcdef, 8);
  CAN.write(buf, 8);
  CAN.endPacket();

  Serial.println("done");

  delay(1000);

}
`

**Comment by ReinierG** [comment]
Similar issue here. ESP32 board. CAN bus at 250 kbps. ESP32 can only send and receive CAN messages when initialized with 500E3.

**Comment by BlackBrix** [comment]
same issue here :-/
with Feather M4 CAN Board

**Comment by caternuson** [comment]
ESP32 support is known to be broken.

For the Feather M4 CAN, please try using the new library here:
https://github.com/adafruit/Adafruit_CAN
If the same issue occurs, please open a new issue there.

This library is being deprecated.
