### ISSUE TITLE
add booster enable to examples

### ISSUE THREAD

**Issue by mikeysklar** [adafruit/arduino-CAN#9]
The CANReceiver and CANSender examples do not include booster enable for the Adafruit M4 CAN board. Can that be added (even in comments) to reduce confusion? 

`  Serial.println("CAN Sender");
  pinMode(PIN_CAN_STANDBY, OUTPUT);
  digitalWrite(PIN_CAN_STANDBY, false); // turn off STANDBY
  pinMode(PIN_CAN_BOOSTEN, OUTPUT);
  digitalWrite(PIN_CAN_BOOSTEN, true); // turn on booster`

`  Serial.println("CAN Receiver");
  pinMode(PIN_CAN_STANDBY, OUTPUT);
  digitalWrite(PIN_CAN_STANDBY, false); // turn off STANDBY
  pinMode(PIN_CAN_BOOSTEN, OUTPUT);
  digitalWrite(PIN_CAN_BOOSTEN, true); // turn on booster`

**Comment by caternuson** [comment]
Should be fixed in the new library:
https://github.com/adafruit/Adafruit_CAN
